enableGlobalCache: false

npmPreapprovedPackages:
  - '@zyno-io/ts-reflection@26.803.2224'
  - '@zyno-io/ts-server-foundation@26.803.2224'

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.18.0.cjs
